### ISSUE TITLE
"SyntalxTreeNode" object not iterable error

### ISSUE THREAD

**Issue by NirvikNU** [analysiscenter/pydens#16]
While running the solved example:
```
import os
import warnings
import sys

warnings.filterwarnings('ignore')
from tensorflow import logging
logging.set_verbosity(logging.ERROR)
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import numpy as np
import tensorflow as tf
from tqdm import tqdm_notebook
import matplotlib.pyplot as plt

sys.path.append('..')
from pydens import Solver, NumpySampler, cart_prod
from pydens import plot_loss, plot_2d, plot_pair_1d, plot_sections_2d, plot_sections_3d

from pydens import add_tokens
add_tokens()

# describing pde-problem in pde-dict
pde = {'n_dims': 1,
       'form': lambda u, t: D(u, t) - 2 * np.pi * cos(2 * np.pi * t),
       'initial_condition': 1 # will be transformed into callable returning 1
      }

# put it together in model-config
config = {'pde': pde,
          'track': {'dt': lambda u, t: D(u, t)}}

# uniform sampling scheme
s = NumpySampler('uniform')

#
## train the network on batches of 100 points
dg = Solver(config)
```

I run into the following error:
`TypeError: 'SyntaxTreeNode' object is not iterable`

The stacktrace is:
````Traceback (most recent call last):
File "<ipython-input-21-1b5c74329633>", line 1, in <module>
    runfile('/home/nirvik/Documents/neuronal_model_python/temp.py', wdir='/home/nirvik/Documents/neuronal_model_python')

  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/nirvik/Documents/neuronal_model_python/temp.py", line 38, in <module>
    dg = Solver(config)

  File "/home/nirvik/.local/lib/python3.6/site-packages/pydens/wrapper.py", line 21, in __init__
    self.model = model_class(config)

  File "/home/nirvik/.local/lib/python3.6/site-packages/pydens/batchflow/batchflow/models/tf/base.py", line 262, in __init__
    super().__init__(*args, **kwargs)

  File "/home/nirvik/.local/lib/python3.6/site-packages/pydens/batchflow/batchflow/models/base.py", line 38, in __init__
    self.build(*args, **kwargs)

  File "/home/nirvik/.local/lib/python3.6/site-packages/pydens/batchflow/batchflow/models/tf/base.py", line 331, in build
    config = self.build_config()

  File "/home/nirvik/.local/lib/python3.6/site-packages/pydens/model_tf.py", line 117, in build_config
    n_parameters = get_num_parameters(form[0])

  File "/home/nirvik/.local/lib/python3.6/site-packages/pydens/syntax_tree.py", line 77, in get_num_parameters
    tree = form(*[SyntaxTreeNode('_' + str(i)) for i in range(n_args)])

  File "/home/nirvik/Documents/neuronal_model_python/temp.py", line 25, in <lambda>
    'form': lambda u, t: D(u, t) - 2 * np.pi * 2 * t^3,

  File "/home/nirvik/.local/lib/python3.6/site-packages/pydens/tokens.py", line 63, in <lambda>
    if isinstance(args[0], SyntaxTreeNode) else method_(*args, **kwargs))

  File "/home/nirvik/.local/lib/python3.6/site-packages/pydens/letters.py", line 82, in D
    return np.stack([self.D(func, coordinate) for coordinate in coordinates],
```

I am new to using this package...please help.

**Comment by akoryagin** [comment]
Hey, @NirvikNU, thanks for the issue!

Judging by this line in the traceback
```
'form': lambda u, t: D(u, t) - 2 * np.pi * 2 * t^3
```
you're trying to solve an equation with `t` cubed in the right-hand side of the equation. The thing is, exponentiation in `Python` is performed using double stars `**`. So, the line should look like
```
'form': lambda u, t: D(u, t) - 2 * np.pi * 2 * t**3
```

Best,
Alex

**Comment by NirvikNU** [comment]
Sorry for posting the wrong traceback, this is the correct one:
```
Traceback (most recent call last):

  File "<ipython-input-26-1b5c74329633>", line 1, in <module>
    runfile('/home/nirvik/Documents/neuronal_model_python/temp.py', wdir='/home/nirvik/Documents/neuronal_model_python')

  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/nirvik/Documents/neuronal_model_python/temp.py", line 38, in <module>
    dg = Solver(config)

  File "/home/nirvik/.local/lib/python3.6/site-packages/pydens/wrapper.py", line 21, in __init__
    self.model = model_class(config)

  File "/home/nirvik/.local/lib/python3.6/site-packages/pydens/batchflow/batchflow/models/tf/base.py", line 262, in __init__
    super().__init__(*args, **kwargs)

  File "/home/nirvik/.local/lib/python3.6/site-packages/pydens/batchflow/batchflow/models/base.py", line 38, in __init__
    self.build(*args, **kwargs)

  File "/home/nirvik/.local/lib/python3.6/site-packages/pydens/batchflow/batchflow/models/tf/base.py", line 331, in build
    config = self.build_config()

  File "/home/nirvik/.local/lib/python3.6/site-packages/pydens/model_tf.py", line 117, in build_config
    n_parameters = get_num_parameters(form[0])

  File "/home/nirvik/.local/lib/python3.6/site-packages/pydens/syntax_tree.py", line 77, in get_num_parameters
    tree = form(*[SyntaxTreeNode('_' + str(i)) for i in range(n_args)])

  File "/home/nirvik/Documents/neuronal_model_python/temp.py", line 25, in <lambda>
    'form': lambda u, t: D(u, t) - 2 * np.pi * 2*t**3,

  File "/home/nirvik/.local/lib/python3.6/site-packages/pydens/tokens.py", line 63, in <lambda>
    if isinstance(args[0], SyntaxTreeNode) else method_(*args, **kwargs))

  File "/home/nirvik/.local/lib/python3.6/site-packages/pydens/letters.py", line 82, in D
    return np.stack([self.D(func, coordinate) for coordinate in coordinates],

TypeError: 'SyntaxTreeNode' object is not iterable
```

Also the same error persists with the original solved example for ODE I posted above.
